# -------- $Frist$ $import$ $important$ $Libraries$ ------

In [22]:
import numpy  as ny
import pandas as pd

# 1.*-------------- Load Dataset --------------*

In [23]:
df = pd.read_csv('heart_disease_health_indicators_BRFSS2015 2 (1).csv')
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0,1,1,1,40,1,0,0,0,0,...,1,0,5,18,15,1,0,9,4,3
1,0,0,0,0,25,1,0,0,1,0,...,0,1,3,0,0,0,0,7,6,1
2,0,1,1,1,28,0,0,0,0,1,...,1,1,5,30,30,1,0,9,4,8
3,0,1,0,1,27,0,0,0,1,1,...,1,0,2,0,0,0,0,11,3,6
4,0,1,1,1,24,0,0,0,1,1,...,1,0,2,3,0,0,0,11,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0,1,1,1,45,0,0,0,0,1,...,1,0,3,0,5,0,1,5,6,7
253676,0,1,1,1,18,0,0,2,0,0,...,1,0,4,0,0,1,0,11,2,4
253677,0,0,0,1,28,0,0,0,1,1,...,1,0,1,0,0,0,0,2,5,2
253678,0,1,0,1,23,0,0,0,0,1,...,1,0,3,0,0,0,1,7,5,1
253679,1,1,1,1,25,0,0,2,1,1,...,1,0,2,0,0,0,0,9,6,2

# 2. *--------- Perform EDA ----------*

In [24]:
df.head

<bound method NDFrame.head of         HeartDiseaseorAttack  HighBP  HighChol  CholCheck  BMI  Smoker  \
0                          0       1         1          1   40       1
1                          0       0         0          0   25       1
2                          0       1         1          1   28       0
3                          0       1         0          1   27       0
4                          0       1         1          1   24       0
...                      ...     ...       ...        ...  ...     ...
253675                     0       1         1          1   45       0
253676                     0       1         1          1   18       0
253677                     0       0         0          1   28       0
253678                     0       1         0          1   23       0
253679                     1       1         1          1   25       0

        Stroke  Diabetes  PhysActivity  Fruits  ...  AnyHealthcare  \
0            0         0             0       0  ...              1
1            0         0             1       0  ...              0
2            0         0             0       1  ...              1
3            0         0             1       1  ...              1
4            0         0             1       1  ...              1
...        ...       ...           ...     ...  ...            ...
253675       0         0             0       1  ...              1
253676       0         2             0       0  ...              1
253677       0         0             1       1  ...              1
253678       0         0             0       1  ...              1
253679       0         2             1       1  ...              1

        NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex  Age  \
0                 0        5        18        15         1    0    9
1                 1        3         0         0         0    0    7
2                 1        5        30        30         1    0    9
3                 0        2         0         0         0    0   11
4                 0        2         3         0         0    0   11
...             ...      ...       ...       ...       ...  ...  ...
253675            0        3         0         5         0    1    5
253676            0        4         0         0         1    0   11
253677            0        1         0         0         0    0    2
253678            0        3         0         0         0    1    7
253679            0        2         0         0         0    0    9

        Education  Income
0               4       3
1               6       1
2               4       8
3               3       6
4               5       4
...           ...     ...
253675          6       7
253676          2       4
253677          5       2
253678          5       1
253679          6       2

[253680 rows x 22 columns]>

In [25]:
df.shape

(253680, 22)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   HeartDiseaseorAttack  253680 non-null  int64
 1   HighBP                253680 non-null  int64
 2   HighChol              253680 non-null  int64
 3   CholCheck             253680 non-null  int64
 4   BMI                   253680 non-null  int64
 5   Smoker                253680 non-null  int64
 6   Stroke                253680 non-null  int64
 7   Diabetes              253680 non-null  int64
 8   PhysActivity          253680 non-null  int64
 9   Fruits                253680 non-null  int64
 10  Veggies               253680 non-null  int64
 11  HvyAlcoholConsump     253680 non-null  int64
 12  AnyHealthcare         253680 non-null  int64
 13  NoDocbcCost           253680 non-null  int64
 14  GenHlth               253680 non-null  int64
 15  MentHlth              253680 non-null  int64
 16  PhysHlth              253680 non-null  int64
 17  DiffWalk              253680 non-null  int64
 18  Sex                   253680 non-null  int64
 19  Age                   253680 non-null  int64
 20  Education             253680 non-null  int64
 21  Income                253680 non-null  int64
dtypes: int64(22)
memory usage: 42.6 MB

In [27]:
df.describe()

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
count,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,...,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000
mean,0.094186,0.429001,0.424121,0.962670,28.382364,0.443169,0.040571,0.296921,0.756544,0.634256,...,0.951053,0.084177,2.511392,3.184772,4.242081,0.168224,0.440342,8.032119,5.050434,6.053875
std,0.292087,0.494934,0.494210,0.189571,6.608694,0.496761,0.197294,0.698160,0.429169,0.481639,...,0.215759,0.277654,1.068477,7.412847,8.717951,0.374066,0.496429,3.054220,0.985774,2.071148
min,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,1.000000,24.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,6.000000,4.000000,5.000000
50%,0.000000,0.000000,0.000000,1.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,8.000000,5.000000,7.000000
75%,0.000000,1.000000,1.000000,1.000000,31.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,3.000000,2.000000,3.000000,0.000000,1.000000,10.000000,6.000000,8.000000
max,1.000000,1.000000,1.000000,1.000000,98.000000,1.000000,1.000000,2.000000,1.000000,1.000000,...,1.000000,1.000000,5.000000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000

In [28]:
df.select_dtypes(include= 'object').sum()

Series([], dtype: float64)

In [29]:
df.select_dtypes(include='number').sum()

HeartDiseaseorAttack      23893
HighBP                   108829
HighChol                 107591
CholCheck                244210
BMI                     7200038
Smoker                   112423
Stroke                    10292
Diabetes                  75323
PhysActivity             191920
Fruits                   160898
Veggies                  205841
HvyAlcoholConsump         14256
AnyHealthcare            241263
NoDocbcCost               21354
GenHlth                  637090
MentHlth                 807913
PhysHlth                1076131
DiffWalk                  42675
Sex                      111706
Age                     2037588
Education               1281194
Income                  1535747
dtype: int64

# 3. * -----== Check Null values ==-----*

In [30]:
df.isnull().sum()

HeartDiseaseorAttack    0
HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
Diabetes                0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
dtype: int64

# 4. * ------ Convert dataset inot Understandable fomat -------

In [31]:
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0,1,1,1,40,1,0,0,0,0,...,1,0,5,18,15,1,0,9,4,3
1,0,0,0,0,25,1,0,0,1,0,...,0,1,3,0,0,0,0,7,6,1
2,0,1,1,1,28,0,0,0,0,1,...,1,1,5,30,30,1,0,9,4,8
3,0,1,0,1,27,0,0,0,1,1,...,1,0,2,0,0,0,0,11,3,6
4,0,1,1,1,24,0,0,0,1,1,...,1,0,2,3,0,0,0,11,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0,1,1,1,45,0,0,0,0,1,...,1,0,3,0,5,0,1,5,6,7
253676,0,1,1,1,18,0,0,2,0,0,...,1,0,4,0,0,1,0,11,2,4
253677,0,0,0,1,28,0,0,0,1,1,...,1,0,1,0,0,0,0,2,5,2
253678,0,1,0,1,23,0,0,0,0,1,...,1,0,3,0,0,0,1,7,5,1
253679,1,1,1,1,25,0,0,2,1,1,...,1,0,2,0,0,0,0,9,6,2

In [32]:
cols = ['HeartDiseaseorAttack', 'HighBP', 'HighChol', 'CholCheck',
        'Smoker', 'Stroke', 'PhysActivity', 'Fruits', 'Veggies',
        'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'DiffWalk']

df[cols] = df[cols].replace({1: 'Yes', 0: 'No'})

 ### Here we can clearly see the diffrence..

In [33]:
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,No,Yes,Yes,Yes,40,Yes,No,0,No,No,...,Yes,No,5,18,15,Yes,0,9,4,3
1,No,No,No,No,25,Yes,No,0,Yes,No,...,No,Yes,3,0,0,No,0,7,6,1
2,No,Yes,Yes,Yes,28,No,No,0,No,Yes,...,Yes,Yes,5,30,30,Yes,0,9,4,8
3,No,Yes,No,Yes,27,No,No,0,Yes,Yes,...,Yes,No,2,0,0,No,0,11,3,6
4,No,Yes,Yes,Yes,24,No,No,0,Yes,Yes,...,Yes,No,2,3,0,No,0,11,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,No,Yes,Yes,Yes,45,No,No,0,No,Yes,...,Yes,No,3,0,5,No,1,5,6,7
253676,No,Yes,Yes,Yes,18,No,No,2,No,No,...,Yes,No,4,0,0,Yes,0,11,2,4
253677,No,No,No,Yes,28,No,No,0,Yes,Yes,...,Yes,No,1,0,0,No,0,2,5,2
253678,No,Yes,No,Yes,23,No,No,0,No,Yes,...,Yes,No,3,0,0,No,1,7,5,1
253679,Yes,Yes,Yes,Yes,25,No,No,2,Yes,Yes,...,Yes,No,2,0,0,No,0,9,6,2

In [34]:
df.info() # It also changes there data type automaticaly.. as you can see

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   HeartDiseaseorAttack  253680 non-null  object
 1   HighBP                253680 non-null  object
 2   HighChol              253680 non-null  object
 3   CholCheck             253680 non-null  object
 4   BMI                   253680 non-null  int64
 5   Smoker                253680 non-null  object
 6   Stroke                253680 non-null  object
 7   Diabetes              253680 non-null  int64
 8   PhysActivity          253680 non-null  object
 9   Fruits                253680 non-null  object
 10  Veggies               253680 non-null  object
 11  HvyAlcoholConsump     253680 non-null  object
 12  AnyHealthcare         253680 non-null  object
 13  NoDocbcCost           253680 non-null  object
 14  GenHlth               253680 non-null  int64
 15  MentHlth              253680 non-null  int64
 16  PhysHlth              253680 non-null  int64
 17  DiffWalk              253680 non-null  object
 18  Sex                   253680 non-null  int64
 19  Age                   253680 non-null  int64
 20  Education             253680 non-null  int64
 21  Income                253680 non-null  int64
dtypes: int64(9), object(13)
memory usage: 42.6+ MB

In [35]:
df['Sex'] = df['Sex'].map({0:'Female',1:'Male'})   # It's a second type of mathod we can also do in this way or using map..
df

# df['Sex'] = df['Sex'].replace({1:'Male',0:'Feamale'})
# df

#df['Sex'] = df['Sex'].apply(lambda x : 'Male' if x == 1 else 'Female')
#df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,No,Yes,Yes,Yes,40,Yes,No,0,No,No,...,Yes,No,5,18,15,Yes,Female,9,4,3
1,No,No,No,No,25,Yes,No,0,Yes,No,...,No,Yes,3,0,0,No,Female,7,6,1
2,No,Yes,Yes,Yes,28,No,No,0,No,Yes,...,Yes,Yes,5,30,30,Yes,Female,9,4,8
3,No,Yes,No,Yes,27,No,No,0,Yes,Yes,...,Yes,No,2,0,0,No,Female,11,3,6
4,No,Yes,Yes,Yes,24,No,No,0,Yes,Yes,...,Yes,No,2,3,0,No,Female,11,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,No,Yes,Yes,Yes,45,No,No,0,No,Yes,...,Yes,No,3,0,5,No,Male,5,6,7
253676,No,Yes,Yes,Yes,18,No,No,2,No,No,...,Yes,No,4,0,0,Yes,Female,11,2,4
253677,No,No,No,Yes,28,No,No,0,Yes,Yes,...,Yes,No,1,0,0,No,Female,2,5,2
253678,No,Yes,No,Yes,23,No,No,0,No,Yes,...,Yes,No,3,0,0,No,Male,7,5,1
253679,Yes,Yes,Yes,Yes,25,No,No,2,Yes,Yes,...,Yes,No,2,0,0,No,Female,9,6,2

In [36]:
df['Diabetes'] = df['Diabetes'].apply(lambda x :'No diabetes' if x == 0 
                                      else('Prediabetes' if x == 1 else 'Yes_Diabetes'))
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,No,Yes,Yes,Yes,40,Yes,No,No diabetes,No,No,...,Yes,No,5,18,15,Yes,Female,9,4,3
1,No,No,No,No,25,Yes,No,No diabetes,Yes,No,...,No,Yes,3,0,0,No,Female,7,6,1
2,No,Yes,Yes,Yes,28,No,No,No diabetes,No,Yes,...,Yes,Yes,5,30,30,Yes,Female,9,4,8
3,No,Yes,No,Yes,27,No,No,No diabetes,Yes,Yes,...,Yes,No,2,0,0,No,Female,11,3,6
4,No,Yes,Yes,Yes,24,No,No,No diabetes,Yes,Yes,...,Yes,No,2,3,0,No,Female,11,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,No,Yes,Yes,Yes,45,No,No,No diabetes,No,Yes,...,Yes,No,3,0,5,No,Male,5,6,7
253676,No,Yes,Yes,Yes,18,No,No,Yes_Diabetes,No,No,...,Yes,No,4,0,0,Yes,Female,11,2,4
253677,No,No,No,Yes,28,No,No,No diabetes,Yes,Yes,...,Yes,No,1,0,0,No,Female,2,5,2
253678,No,Yes,No,Yes,23,No,No,No diabetes,No,Yes,...,Yes,No,3,0,0,No,Male,7,5,1
253679,Yes,Yes,Yes,Yes,25,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,0,0,No,Female,9,6,2

In [37]:
df['Education'] = df['Education'].replace({1 : 'No_sch_or_KG', 
                                           2 :'1-8 (Elementary)',
                                           3 :'9-11 (Some high school)',
                                           4 :'High_sch/Graduate)',
                                           5 :'SomeCollege/Tec(1-3)',
                                           6 :'College_Gradu(4+years)'})

In [38]:
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,No,Yes,Yes,Yes,40,Yes,No,No diabetes,No,No,...,Yes,No,5,18,15,Yes,Female,9,High_sch/Graduate),3
1,No,No,No,No,25,Yes,No,No diabetes,Yes,No,...,No,Yes,3,0,0,No,Female,7,College_Gradu(4+years),1
2,No,Yes,Yes,Yes,28,No,No,No diabetes,No,Yes,...,Yes,Yes,5,30,30,Yes,Female,9,High_sch/Graduate),8
3,No,Yes,No,Yes,27,No,No,No diabetes,Yes,Yes,...,Yes,No,2,0,0,No,Female,11,9-11 (Some high school),6
4,No,Yes,Yes,Yes,24,No,No,No diabetes,Yes,Yes,...,Yes,No,2,3,0,No,Female,11,SomeCollege/Tec(1-3),4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,No,Yes,Yes,Yes,45,No,No,No diabetes,No,Yes,...,Yes,No,3,0,5,No,Male,5,College_Gradu(4+years),7
253676,No,Yes,Yes,Yes,18,No,No,Yes_Diabetes,No,No,...,Yes,No,4,0,0,Yes,Female,11,1-8 (Elementary),4
253677,No,No,No,Yes,28,No,No,No diabetes,Yes,Yes,...,Yes,No,1,0,0,No,Female,2,SomeCollege/Tec(1-3),2
253678,No,Yes,No,Yes,23,No,No,No diabetes,No,Yes,...,Yes,No,3,0,0,No,Male,7,SomeCollege/Tec(1-3),1
253679,Yes,Yes,Yes,Yes,25,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,0,0,No,Female,9,College_Gradu(4+years),2

In [39]:
df['Income'] = df['Income'].replace({1:'$2,00-$10,000',
                                    2:'$10,000-$15,000',
                                    3:'$15,000-$20,000)',
                                    4:'$20,000-$25,000)'

                                    })
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,No,Yes,Yes,Yes,40,Yes,No,No diabetes,No,No,...,Yes,No,5,18,15,Yes,Female,9,High_sch/Graduate),"$15,000-$20,000)"
1,No,No,No,No,25,Yes,No,No diabetes,Yes,No,...,No,Yes,3,0,0,No,Female,7,College_Gradu(4+years),"$2,00-$10,000"
2,No,Yes,Yes,Yes,28,No,No,No diabetes,No,Yes,...,Yes,Yes,5,30,30,Yes,Female,9,High_sch/Graduate),8
3,No,Yes,No,Yes,27,No,No,No diabetes,Yes,Yes,...,Yes,No,2,0,0,No,Female,11,9-11 (Some high school),6
4,No,Yes,Yes,Yes,24,No,No,No diabetes,Yes,Yes,...,Yes,No,2,3,0,No,Female,11,SomeCollege/Tec(1-3),"$20,000-$25,000)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,No,Yes,Yes,Yes,45,No,No,No diabetes,No,Yes,...,Yes,No,3,0,5,No,Male,5,College_Gradu(4+years),7
253676,No,Yes,Yes,Yes,18,No,No,Yes_Diabetes,No,No,...,Yes,No,4,0,0,Yes,Female,11,1-8 (Elementary),"$20,000-$25,000)"
253677,No,No,No,Yes,28,No,No,No diabetes,Yes,Yes,...,Yes,No,1,0,0,No,Female,2,SomeCollege/Tec(1-3),"$10,000-$15,000"
253678,No,Yes,No,Yes,23,No,No,No diabetes,No,Yes,...,Yes,No,3,0,0,No,Male,7,SomeCollege/Tec(1-3),"$2,00-$10,000"
253679,Yes,Yes,Yes,Yes,25,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,0,0,No,Female,9,College_Gradu(4+years),"$10,000-$15,000"

In [40]:
df.head(10)

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,No,Yes,Yes,Yes,40,Yes,No,No diabetes,No,No,...,Yes,No,5,18,15,Yes,Female,9,High_sch/Graduate),"$15,000-$20,000)"
1,No,No,No,No,25,Yes,No,No diabetes,Yes,No,...,No,Yes,3,0,0,No,Female,7,College_Gradu(4+years),"$2,00-$10,000"
2,No,Yes,Yes,Yes,28,No,No,No diabetes,No,Yes,...,Yes,Yes,5,30,30,Yes,Female,9,High_sch/Graduate),8
3,No,Yes,No,Yes,27,No,No,No diabetes,Yes,Yes,...,Yes,No,2,0,0,No,Female,11,9-11 (Some high school),6
4,No,Yes,Yes,Yes,24,No,No,No diabetes,Yes,Yes,...,Yes,No,2,3,0,No,Female,11,SomeCollege/Tec(1-3),"$20,000-$25,000)"
5,No,Yes,Yes,Yes,25,Yes,No,No diabetes,Yes,Yes,...,Yes,No,2,0,2,No,Male,10,College_Gradu(4+years),8
6,No,Yes,No,Yes,30,Yes,No,No diabetes,No,No,...,Yes,No,3,0,14,No,Female,9,College_Gradu(4+years),7
7,No,Yes,Yes,Yes,25,Yes,No,No diabetes,Yes,No,...,Yes,No,3,0,0,Yes,Female,11,High_sch/Graduate),"$20,000-$25,000)"
8,Yes,Yes,Yes,Yes,30,Yes,No,Yes_Diabetes,No,Yes,...,Yes,No,5,30,30,Yes,Female,9,SomeCollege/Tec(1-3),"$2,00-$10,000"
9,No,No,No,Yes,24,No,No,No diabetes,No,No,...,Yes,No,2,0,0,No,Male,8,High_sch/Graduate),"$15,000-$20,000)"

In [41]:
df.columns

Index(['HeartDiseaseorAttack', 'HighBP', 'HighChol', 'CholCheck', 'BMI',
       'Smoker', 'Stroke', 'Diabetes', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

In [42]:
df = df.drop(columns=['ID', 'Timestamp'], errors='ignore')
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,No,Yes,Yes,Yes,40,Yes,No,No diabetes,No,No,...,Yes,No,5,18,15,Yes,Female,9,High_sch/Graduate),"$15,000-$20,000)"
1,No,No,No,No,25,Yes,No,No diabetes,Yes,No,...,No,Yes,3,0,0,No,Female,7,College_Gradu(4+years),"$2,00-$10,000"
2,No,Yes,Yes,Yes,28,No,No,No diabetes,No,Yes,...,Yes,Yes,5,30,30,Yes,Female,9,High_sch/Graduate),8
3,No,Yes,No,Yes,27,No,No,No diabetes,Yes,Yes,...,Yes,No,2,0,0,No,Female,11,9-11 (Some high school),6
4,No,Yes,Yes,Yes,24,No,No,No diabetes,Yes,Yes,...,Yes,No,2,3,0,No,Female,11,SomeCollege/Tec(1-3),"$20,000-$25,000)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,No,Yes,Yes,Yes,45,No,No,No diabetes,No,Yes,...,Yes,No,3,0,5,No,Male,5,College_Gradu(4+years),7
253676,No,Yes,Yes,Yes,18,No,No,Yes_Diabetes,No,No,...,Yes,No,4,0,0,Yes,Female,11,1-8 (Elementary),"$20,000-$25,000)"
253677,No,No,No,Yes,28,No,No,No diabetes,Yes,Yes,...,Yes,No,1,0,0,No,Female,2,SomeCollege/Tec(1-3),"$10,000-$15,000"
253678,No,Yes,No,Yes,23,No,No,No diabetes,No,Yes,...,Yes,No,3,0,0,No,Male,7,SomeCollege/Tec(1-3),"$2,00-$10,000"
253679,Yes,Yes,Yes,Yes,25,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,0,0,No,Female,9,College_Gradu(4+years),"$10,000-$15,000"

In [43]:
print(df.info())          # Data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   HeartDiseaseorAttack  253680 non-null  object
 1   HighBP                253680 non-null  object
 2   HighChol              253680 non-null  object
 3   CholCheck             253680 non-null  object
 4   BMI                   253680 non-null  int64
 5   Smoker                253680 non-null  object
 6   Stroke                253680 non-null  object
 7   Diabetes              253680 non-null  object
 8   PhysActivity          253680 non-null  object
 9   Fruits                253680 non-null  object
 10  Veggies               253680 non-null  object
 11  HvyAlcoholConsump     253680 non-null  object
 12  AnyHealthcare         253680 non-null  object
 13  NoDocbcCost           253680 non-null  object
 14  GenHlth               253680 non-null  int64
 15  MentHlth              253680 non-null  int64
 16  PhysHlth              253680 non-null  int64
 17  DiffWalk              253680 non-null  object
 18  Sex                   253680 non-null  object
 19  Age                   253680 non-null  int64
 20  Education             253680 non-null  object
 21  Income                253680 non-null  object
dtypes: int64(5), object(17)
memory usage: 42.6+ MB
None

In [44]:
print(df.nunique())       # Unique values per column

HeartDiseaseorAttack     2
HighBP                   2
HighChol                 2
CholCheck                2
BMI                     84
Smoker                   2
Stroke                   2
Diabetes                 3
PhysActivity             2
Fruits                   2
Veggies                  2
HvyAlcoholConsump        2
AnyHealthcare            2
NoDocbcCost              2
GenHlth                  5
MentHlth                31
PhysHlth                31
DiffWalk                 2
Sex                      2
Age                     13
Education                6
Income                   8
dtype: int64

In [45]:
print(df.head())          # Preview cleaned data

  HeartDiseaseorAttack HighBP HighChol CholCheck  BMI Smoker Stroke  \
0                   No    Yes      Yes       Yes   40    Yes     No
1                   No     No       No        No   25    Yes     No
2                   No    Yes      Yes       Yes   28     No     No
3                   No    Yes       No       Yes   27     No     No
4                   No    Yes      Yes       Yes   24     No     No

      Diabetes PhysActivity Fruits  ... AnyHealthcare NoDocbcCost GenHlth  \
0  No diabetes           No     No  ...           Yes          No       5
1  No diabetes          Yes     No  ...            No         Yes       3
2  No diabetes           No    Yes  ...           Yes         Yes       5
3  No diabetes          Yes    Yes  ...           Yes          No       2
4  No diabetes          Yes    Yes  ...           Yes          No       2

  MentHlth  PhysHlth  DiffWalk     Sex Age                Education  \
0       18        15       Yes  Female   9       High_sch/Graduate)
1        0         0        No  Female   7   College_Gradu(4+years)
2       30        30       Yes  Female   9       High_sch/Graduate)
3        0         0        No  Female  11  9-11 (Some high school)
4        3         0        No  Female  11     SomeCollege/Tec(1-3)

             Income
0  $15,000-$20,000)
1     $2,00-$10,000
2                 8
3                 6
4  $20,000-$25,000)

[5 rows x 22 columns]

In [47]:
df.to_csv('heart_disease_health_indicators_BRFSS2015 2 (1).csv')