In [7]:
import numpy  as ny
import pandas as pd

In [8]:
df = pd.read_csv('heart_disease_health_indicators_BRFSS2015 2 (1).csv')
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0,1,1,1,40,1,0,0,0,0,...,1,0,5,18,15,1,0,9,4,3
1,0,0,0,0,25,1,0,0,1,0,...,0,1,3,0,0,0,0,7,6,1
2,0,1,1,1,28,0,0,0,0,1,...,1,1,5,30,30,1,0,9,4,8
3,0,1,0,1,27,0,0,0,1,1,...,1,0,2,0,0,0,0,11,3,6
4,0,1,1,1,24,0,0,0,1,1,...,1,0,2,3,0,0,0,11,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0,1,1,1,45,0,0,0,0,1,...,1,0,3,0,5,0,1,5,6,7
253676,0,1,1,1,18,0,0,2,0,0,...,1,0,4,0,0,1,0,11,2,4
253677,0,0,0,1,28,0,0,0,1,1,...,1,0,1,0,0,0,0,2,5,2
253678,0,1,0,1,23,0,0,0,0,1,...,1,0,3,0,0,0,1,7,5,1
253679,1,1,1,1,25,0,0,2,1,1,...,1,0,2,0,0,0,0,9,6,2

In [9]:
df.columns

Index(['HeartDiseaseorAttack', 'HighBP', 'HighChol', 'CholCheck', 'BMI',
       'Smoker', 'Stroke', 'Diabetes', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

In [10]:
df.columns == 'object'

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [11]:
df.dtypes

HeartDiseaseorAttack    int64
HighBP                  int64
HighChol                int64
CholCheck               int64
BMI                     int64
Smoker                  int64
Stroke                  int64
Diabetes                int64
PhysActivity            int64
Fruits                  int64
Veggies                 int64
HvyAlcoholConsump       int64
AnyHealthcare           int64
NoDocbcCost             int64
GenHlth                 int64
MentHlth                int64
PhysHlth                int64
DiffWalk                int64
Sex                     int64
Age                     int64
Education               int64
Income                  int64
dtype: object

In [49]:
cols = ['HeartDiseaseorAttack', 'HighBP', 'HighChol', 'CholCheck',
        'Smoker', 'Stroke', 'PhysActivity', 'Fruits', 'Veggies',
        'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'DiffWalk']

df[cols] = df[cols].replace({1: 'Yes', 0: 'No'})

In [51]:
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,No,Yes,Yes,Yes,40,Yes,No,No diabetes,No,No,...,Yes,No,5,18,15,Yes,Female,9,High_sch/Graduate),"$15,000-$20,000)"
1,No,No,No,No,25,Yes,No,No diabetes,Yes,No,...,No,Yes,3,0,0,No,Female,7,College_Gradu(4+years),"$2,00-$10,000"
2,No,Yes,Yes,Yes,28,No,No,No diabetes,No,Yes,...,Yes,Yes,5,30,30,Yes,Female,9,High_sch/Graduate),8
3,No,Yes,No,Yes,27,No,No,No diabetes,Yes,Yes,...,Yes,No,2,0,0,No,Female,11,9-11 (Some high school),6
4,No,Yes,Yes,Yes,24,No,No,No diabetes,Yes,Yes,...,Yes,No,2,3,0,No,Female,11,SomeCollege/Tec(1-3),"$20,000-$25,000)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,No,Yes,Yes,Yes,45,No,No,No diabetes,No,Yes,...,Yes,No,3,0,5,No,Male,5,College_Gradu(4+years),7
253676,No,Yes,Yes,Yes,18,No,No,Yes_Diabetes,No,No,...,Yes,No,4,0,0,Yes,Female,11,1-8 (Elementary),"$20,000-$25,000)"
253677,No,No,No,Yes,28,No,No,No diabetes,Yes,Yes,...,Yes,No,1,0,0,No,Female,2,SomeCollege/Tec(1-3),"$10,000-$15,000"
253678,No,Yes,No,Yes,23,No,No,No diabetes,No,Yes,...,Yes,No,3,0,0,No,Male,7,SomeCollege/Tec(1-3),"$2,00-$10,000"
253679,Yes,Yes,Yes,Yes,25,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,0,0,No,Female,9,College_Gradu(4+years),"$10,000-$15,000"

In [54]:
df['Sex'] = df['Sex'].map({0:'Female',1:'Male'})
df

# df['Sex'] = df['Sex'].replace({1:'Male',0:'Feamale'})
# df

#df['Sex'] = df['Sex'].apply(lambda x : 'Male' if x == 1 else 'Female')
#df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,No,Yes,Yes,Yes,40,Yes,No,No diabetes,No,No,...,Yes,No,5,18,15,Yes,NaN,9,High_sch/Graduate),"$15,000-$20,000)"
1,No,No,No,No,25,Yes,No,No diabetes,Yes,No,...,No,Yes,3,0,0,No,NaN,7,College_Gradu(4+years),"$2,00-$10,000"
2,No,Yes,Yes,Yes,28,No,No,No diabetes,No,Yes,...,Yes,Yes,5,30,30,Yes,NaN,9,High_sch/Graduate),8
3,No,Yes,No,Yes,27,No,No,No diabetes,Yes,Yes,...,Yes,No,2,0,0,No,NaN,11,9-11 (Some high school),6
4,No,Yes,Yes,Yes,24,No,No,No diabetes,Yes,Yes,...,Yes,No,2,3,0,No,NaN,11,SomeCollege/Tec(1-3),"$20,000-$25,000)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,No,Yes,Yes,Yes,45,No,No,No diabetes,No,Yes,...,Yes,No,3,0,5,No,NaN,5,College_Gradu(4+years),7
253676,No,Yes,Yes,Yes,18,No,No,Yes_Diabetes,No,No,...,Yes,No,4,0,0,Yes,NaN,11,1-8 (Elementary),"$20,000-$25,000)"
253677,No,No,No,Yes,28,No,No,No diabetes,Yes,Yes,...,Yes,No,1,0,0,No,NaN,2,SomeCollege/Tec(1-3),"$10,000-$15,000"
253678,No,Yes,No,Yes,23,No,No,No diabetes,No,Yes,...,Yes,No,3,0,0,No,NaN,7,SomeCollege/Tec(1-3),"$2,00-$10,000"
253679,Yes,Yes,Yes,Yes,25,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,0,0,No,NaN,9,College_Gradu(4+years),"$10,000-$15,000"

In [56]:
df['Diabetes'] = df['Diabetes'].apply(lambda x :'No diabetes' if x == 0 
                                      else('Prediabetes' if x == 1 else 'Yes_Diabetes'))
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,No,Yes,Yes,Yes,40,Yes,No,Yes_Diabetes,No,No,...,Yes,No,5,18,15,Yes,NaN,9,High_sch/Graduate),"$15,000-$20,000)"
1,No,No,No,No,25,Yes,No,Yes_Diabetes,Yes,No,...,No,Yes,3,0,0,No,NaN,7,College_Gradu(4+years),"$2,00-$10,000"
2,No,Yes,Yes,Yes,28,No,No,Yes_Diabetes,No,Yes,...,Yes,Yes,5,30,30,Yes,NaN,9,High_sch/Graduate),8
3,No,Yes,No,Yes,27,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,0,0,No,NaN,11,9-11 (Some high school),6
4,No,Yes,Yes,Yes,24,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,3,0,No,NaN,11,SomeCollege/Tec(1-3),"$20,000-$25,000)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,No,Yes,Yes,Yes,45,No,No,Yes_Diabetes,No,Yes,...,Yes,No,3,0,5,No,NaN,5,College_Gradu(4+years),7
253676,No,Yes,Yes,Yes,18,No,No,Yes_Diabetes,No,No,...,Yes,No,4,0,0,Yes,NaN,11,1-8 (Elementary),"$20,000-$25,000)"
253677,No,No,No,Yes,28,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,1,0,0,No,NaN,2,SomeCollege/Tec(1-3),"$10,000-$15,000"
253678,No,Yes,No,Yes,23,No,No,Yes_Diabetes,No,Yes,...,Yes,No,3,0,0,No,NaN,7,SomeCollege/Tec(1-3),"$2,00-$10,000"
253679,Yes,Yes,Yes,Yes,25,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,0,0,No,NaN,9,College_Gradu(4+years),"$10,000-$15,000"

In [58]:
df['Education'] = df['Education'].replace({1 : 'No_sch_or_KG', 
                                           2 :'1-8 (Elementary)',
                                           3 :'9-11 (Some high school)',
                                           4 :'High_sch/Graduate)',
                                           5 :'SomeCollege/Tec(1-3)',
                                           6 :'College_Gradu(4+years)'})

In [60]:
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,No,Yes,Yes,Yes,40,Yes,No,Yes_Diabetes,No,No,...,Yes,No,5,18,15,Yes,NaN,9,High_sch/Graduate),"$15,000-$20,000)"
1,No,No,No,No,25,Yes,No,Yes_Diabetes,Yes,No,...,No,Yes,3,0,0,No,NaN,7,College_Gradu(4+years),"$2,00-$10,000"
2,No,Yes,Yes,Yes,28,No,No,Yes_Diabetes,No,Yes,...,Yes,Yes,5,30,30,Yes,NaN,9,High_sch/Graduate),8
3,No,Yes,No,Yes,27,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,0,0,No,NaN,11,9-11 (Some high school),6
4,No,Yes,Yes,Yes,24,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,3,0,No,NaN,11,SomeCollege/Tec(1-3),"$20,000-$25,000)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,No,Yes,Yes,Yes,45,No,No,Yes_Diabetes,No,Yes,...,Yes,No,3,0,5,No,NaN,5,College_Gradu(4+years),7
253676,No,Yes,Yes,Yes,18,No,No,Yes_Diabetes,No,No,...,Yes,No,4,0,0,Yes,NaN,11,1-8 (Elementary),"$20,000-$25,000)"
253677,No,No,No,Yes,28,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,1,0,0,No,NaN,2,SomeCollege/Tec(1-3),"$10,000-$15,000"
253678,No,Yes,No,Yes,23,No,No,Yes_Diabetes,No,Yes,...,Yes,No,3,0,0,No,NaN,7,SomeCollege/Tec(1-3),"$2,00-$10,000"
253679,Yes,Yes,Yes,Yes,25,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,0,0,No,NaN,9,College_Gradu(4+years),"$10,000-$15,000"

In [62]:
df['Income'] = df['Income'].replace({1:'$2,00-$10,000',
                                    2:'$10,000-$15,000',
                                    3:'$15,000-$20,000)',
                                    4:'$20,000-$25,000)'

                                    })
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,No,Yes,Yes,Yes,40,Yes,No,Yes_Diabetes,No,No,...,Yes,No,5,18,15,Yes,NaN,9,High_sch/Graduate),"$15,000-$20,000)"
1,No,No,No,No,25,Yes,No,Yes_Diabetes,Yes,No,...,No,Yes,3,0,0,No,NaN,7,College_Gradu(4+years),"$2,00-$10,000"
2,No,Yes,Yes,Yes,28,No,No,Yes_Diabetes,No,Yes,...,Yes,Yes,5,30,30,Yes,NaN,9,High_sch/Graduate),8
3,No,Yes,No,Yes,27,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,0,0,No,NaN,11,9-11 (Some high school),6
4,No,Yes,Yes,Yes,24,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,3,0,No,NaN,11,SomeCollege/Tec(1-3),"$20,000-$25,000)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,No,Yes,Yes,Yes,45,No,No,Yes_Diabetes,No,Yes,...,Yes,No,3,0,5,No,NaN,5,College_Gradu(4+years),7
253676,No,Yes,Yes,Yes,18,No,No,Yes_Diabetes,No,No,...,Yes,No,4,0,0,Yes,NaN,11,1-8 (Elementary),"$20,000-$25,000)"
253677,No,No,No,Yes,28,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,1,0,0,No,NaN,2,SomeCollege/Tec(1-3),"$10,000-$15,000"
253678,No,Yes,No,Yes,23,No,No,Yes_Diabetes,No,Yes,...,Yes,No,3,0,0,No,NaN,7,SomeCollege/Tec(1-3),"$2,00-$10,000"
253679,Yes,Yes,Yes,Yes,25,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,0,0,No,NaN,9,College_Gradu(4+years),"$10,000-$15,000"

In [64]:
df.head(10)

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,No,Yes,Yes,Yes,40,Yes,No,Yes_Diabetes,No,No,...,Yes,No,5,18,15,Yes,NaN,9,High_sch/Graduate),"$15,000-$20,000)"
1,No,No,No,No,25,Yes,No,Yes_Diabetes,Yes,No,...,No,Yes,3,0,0,No,NaN,7,College_Gradu(4+years),"$2,00-$10,000"
2,No,Yes,Yes,Yes,28,No,No,Yes_Diabetes,No,Yes,...,Yes,Yes,5,30,30,Yes,NaN,9,High_sch/Graduate),8
3,No,Yes,No,Yes,27,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,0,0,No,NaN,11,9-11 (Some high school),6
4,No,Yes,Yes,Yes,24,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,3,0,No,NaN,11,SomeCollege/Tec(1-3),"$20,000-$25,000)"
5,No,Yes,Yes,Yes,25,Yes,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,0,2,No,NaN,10,College_Gradu(4+years),8
6,No,Yes,No,Yes,30,Yes,No,Yes_Diabetes,No,No,...,Yes,No,3,0,14,No,NaN,9,College_Gradu(4+years),7
7,No,Yes,Yes,Yes,25,Yes,No,Yes_Diabetes,Yes,No,...,Yes,No,3,0,0,Yes,NaN,11,High_sch/Graduate),"$20,000-$25,000)"
8,Yes,Yes,Yes,Yes,30,Yes,No,Yes_Diabetes,No,Yes,...,Yes,No,5,30,30,Yes,NaN,9,SomeCollege/Tec(1-3),"$2,00-$10,000"
9,No,No,No,Yes,24,No,No,Yes_Diabetes,No,No,...,Yes,No,2,0,0,No,NaN,8,High_sch/Graduate),"$15,000-$20,000)"

In [66]:
df.columns

Index(['HeartDiseaseorAttack', 'HighBP', 'HighChol', 'CholCheck', 'BMI',
       'Smoker', 'Stroke', 'Diabetes', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

In [68]:
df = df.drop(columns=['ID', 'Timestamp'], errors='ignore')
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,No,Yes,Yes,Yes,40,Yes,No,Yes_Diabetes,No,No,...,Yes,No,5,18,15,Yes,NaN,9,High_sch/Graduate),"$15,000-$20,000)"
1,No,No,No,No,25,Yes,No,Yes_Diabetes,Yes,No,...,No,Yes,3,0,0,No,NaN,7,College_Gradu(4+years),"$2,00-$10,000"
2,No,Yes,Yes,Yes,28,No,No,Yes_Diabetes,No,Yes,...,Yes,Yes,5,30,30,Yes,NaN,9,High_sch/Graduate),8
3,No,Yes,No,Yes,27,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,0,0,No,NaN,11,9-11 (Some high school),6
4,No,Yes,Yes,Yes,24,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,3,0,No,NaN,11,SomeCollege/Tec(1-3),"$20,000-$25,000)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,No,Yes,Yes,Yes,45,No,No,Yes_Diabetes,No,Yes,...,Yes,No,3,0,5,No,NaN,5,College_Gradu(4+years),7
253676,No,Yes,Yes,Yes,18,No,No,Yes_Diabetes,No,No,...,Yes,No,4,0,0,Yes,NaN,11,1-8 (Elementary),"$20,000-$25,000)"
253677,No,No,No,Yes,28,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,1,0,0,No,NaN,2,SomeCollege/Tec(1-3),"$10,000-$15,000"
253678,No,Yes,No,Yes,23,No,No,Yes_Diabetes,No,Yes,...,Yes,No,3,0,0,No,NaN,7,SomeCollege/Tec(1-3),"$2,00-$10,000"
253679,Yes,Yes,Yes,Yes,25,No,No,Yes_Diabetes,Yes,Yes,...,Yes,No,2,0,0,No,NaN,9,College_Gradu(4+years),"$10,000-$15,000"

In [70]:
print(df.info())          # Data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   HeartDiseaseorAttack  253680 non-null  object
 1   HighBP                253680 non-null  object
 2   HighChol              253680 non-null  object
 3   CholCheck             253680 non-null  object
 4   BMI                   253680 non-null  int64
 5   Smoker                253680 non-null  object
 6   Stroke                253680 non-null  object
 7   Diabetes              253680 non-null  object
 8   PhysActivity          253680 non-null  object
 9   Fruits                253680 non-null  object
 10  Veggies               253680 non-null  object
 11  HvyAlcoholConsump     253680 non-null  object
 12  AnyHealthcare         253680 non-null  object
 13  NoDocbcCost           253680 non-null  object
 14  GenHlth               253680 non-null  int64
 15  MentHlth              253680 non-null  int64
 16  PhysHlth              253680 non-null  int64
 17  DiffWalk              253680 non-null  object
 18  Sex                   0 non-null       object
 19  Age                   253680 non-null  int64
 20  Education             253680 non-null  object
 21  Income                253680 non-null  object
dtypes: int64(5), object(17)
memory usage: 42.6+ MB
None

In [72]:
print(df.isnull().sum())  # Missing values

HeartDiseaseorAttack         0
HighBP                       0
HighChol                     0
CholCheck                    0
BMI                          0
Smoker                       0
Stroke                       0
Diabetes                     0
PhysActivity                 0
Fruits                       0
Veggies                      0
HvyAlcoholConsump            0
AnyHealthcare                0
NoDocbcCost                  0
GenHlth                      0
MentHlth                     0
PhysHlth                     0
DiffWalk                     0
Sex                     253680
Age                          0
Education                    0
Income                       0
dtype: int64

In [74]:
print(df.nunique())       # Unique values per column

HeartDiseaseorAttack     2
HighBP                   2
HighChol                 2
CholCheck                2
BMI                     84
Smoker                   2
Stroke                   2
Diabetes                 1
PhysActivity             2
Fruits                   2
Veggies                  2
HvyAlcoholConsump        2
AnyHealthcare            2
NoDocbcCost              2
GenHlth                  5
MentHlth                31
PhysHlth                31
DiffWalk                 2
Sex                      0
Age                     13
Education                6
Income                   8
dtype: int64

In [76]:
print(df.head())          # Preview cleaned data

  HeartDiseaseorAttack HighBP HighChol CholCheck  BMI Smoker Stroke  \
0                   No    Yes      Yes       Yes   40    Yes     No
1                   No     No       No        No   25    Yes     No
2                   No    Yes      Yes       Yes   28     No     No
3                   No    Yes       No       Yes   27     No     No
4                   No    Yes      Yes       Yes   24     No     No

       Diabetes PhysActivity Fruits  ... AnyHealthcare NoDocbcCost GenHlth  \
0  Yes_Diabetes           No     No  ...           Yes          No       5
1  Yes_Diabetes          Yes     No  ...            No         Yes       3
2  Yes_Diabetes           No    Yes  ...           Yes         Yes       5
3  Yes_Diabetes          Yes    Yes  ...           Yes          No       2
4  Yes_Diabetes          Yes    Yes  ...           Yes          No       2

  MentHlth  PhysHlth  DiffWalk  Sex Age                Education  \
0       18        15       Yes  NaN   9       High_sch/Graduate)
1        0         0        No  NaN   7   College_Gradu(4+years)
2       30        30       Yes  NaN   9       High_sch/Graduate)
3        0         0        No  NaN  11  9-11 (Some high school)
4        3         0        No  NaN  11     SomeCollege/Tec(1-3)

             Income
0  $15,000-$20,000)
1     $2,00-$10,000
2                 8
3                 6
4  $20,000-$25,000)

[5 rows x 22 columns]

# 1. a. Examine Distributions of Individual Variables:
Plot histograms or bar charts to visualize the distribution of key variables such as age, BMI, mental health days (Menthlth), and physical health days (PhysHlth).

# b. Investigate Prevalence of Health Conditions:
Plot bar charts or pie charts to show the prevalence of high blood pressure (HighBP), high cholesterol (HighChol), and other health conditions.

# c. Analyze Distribution of Heart Disease (Target Variable):
Visualize the distribution of heart disease cases using a bar chart or pie chart.

In [8]:
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as p